#!/bin/bash

sips -s format png American_cherry_pxr128.tif --out American_cherry_pxr128.png
sips -s format png American_cherry_pxr128_bmp.tif --out American_cherry_pxr128_bmp.png
sips -s format png American_cherry_pxr128_normal.tif --out American_cherry_pxr128_normal.png
sips -s format png American_oak_pxr128.tif --out American_oak_pxr128.png
sips -s format png American_oak_pxr128_bmp.tif --out American_oak_pxr128_bmp.png
sips -s format png American_oak_pxr128_normal.tif --out American_oak_pxr128_normal.png
sips -s format png American_walnut_pxr128.tif --out American_walnut_pxr128.png
sips -s format png American_walnut_pxr128_bmp.tif --out American_walnut_pxr128_bmp.png
sips -s format png American_walnut_pxr128_normal.tif --out American_walnut_pxr128_normal.png
sips -s format png Anigre_pxr128.tif --out Anigre_pxr128.png
sips -s format png Anigre_pxr128_bmp.tif --out Anigre_pxr128_bmp.png
sips -s format png Anigre_pxr128_normal.tif --out Anigre_pxr128_normal.png
sips -s format png Australian_rosewood_pxr128.tif --out Australian_rosewood_pxr128.png
sips -s format png Australian_rosewood_pxr128_bmp.tif --out Australian_rosewood_pxr128_bmp.png
sips -s format png Australian_rosewood_pxr128_normal.tif --out Australian_rosewood_pxr128_normal.png
sips -s format png Belizan_mahognay_pxr128.tif --out Belizan_mahognay_pxr128.png
sips -s format png Belizan_mahognay_pxr128_bmp.tif --out Belizan_mahognay_pxr128_bmp.png
sips -s format png Belizan_mahognay_pxr128_normal.tif --out Belizan_mahognay_pxr128_normal.png
sips -s format png Brazilian_rosewood_pxr128.tif --out Brazilian_rosewood_pxr128.png
sips -s format png Brazilian_rosewood_pxr128_bmp.tif --out Brazilian_rosewood_pxr128_bmp.png
sips -s format png Brazilian_rosewood_pxr128_normal.tif --out Brazilian_rosewood_pxr128_normal.png
sips -s format png Burled_ash_pxr128.tif --out Burled_ash_pxr128.png
sips -s format png Burled_ash_pxr128_bmp.tif --out Burled_ash_pxr128_bmp.png
sips -s format png Burled_ash_pxr128_normal.tif --out Burled_ash_pxr128_normal.png
sips -s format png Burled_mappa_pxr128.tif --out Burled_mappa_pxr128.png
sips -s format png Burled_mappa_pxr128_bmp.tif --out Burled_mappa_pxr128_bmp.png
sips -s format png Burled_mappa_pxr128_normal.tif --out Burled_mappa_pxr128_normal.png
sips -s format png Burled_olive_ash_pxr128.tif --out Burled_olive_ash_pxr128.png
sips -s format png Burled_olive_ash_pxr128_bmp.tif --out Burled_olive_ash_pxr128_bmp.png
sips -s format png Burled_olive_ash_pxr128_normal.tif --out Burled_olive_ash_pxr128_normal.png
sips -s format png Burled_walnut_pxr128.tif --out Burled_walnut_pxr128.png
sips -s format png Burled_walnut_pxr128_bmp.tif --out Burled_walnut_pxr128_bmp.png
sips -s format png Burled_walnut_pxr128_normal.tif --out Burled_walnut_pxr128_normal.png
sips -s format png Dark_birdseye_maple_pxr128.tif --out Dark_birdseye_maple_pxr128.png
sips -s format png Dark_birdseye_maple_pxr128_bmp.tif --out Dark_birdseye_maple_pxr128_bmp.png
sips -s format png Dark_birdseye_maple_pxr128_normal.tif --out Dark_birdseye_maple_pxr128_normal.png
sips -s format png Figured_birdseye_maple_pxr128.tif --out Figured_birdseye_maple_pxr128.png
sips -s format png Figured_birdseye_maple_pxr128_bmp.tif --out Figured_birdseye_maple_pxr128_bmp.png
sips -s format png Figured_birdseye_maple_pxr128_normal.tif --out Figured_birdseye_maple_pxr128_normal.png
sips -s format png Figured_lacewood_pxr128.tif --out Figured_lacewood_pxr128.png
sips -s format png Figured_lacewood_pxr128_bmp.tif --out Figured_lacewood_pxr128_bmp.png
sips -s format png Figured_lacewood_pxr128_normal.tif --out Figured_lacewood_pxr128_normal.png
sips -s format png Figured_mahogany_pxr128.tif --out Figured_mahogany_pxr128.png
sips -s format png Figured_mahogany_pxr128_bmp.tif --out Figured_mahogany_pxr128_bmp.png
sips -s format png Figured_mahogany_pxr128_normal.tif --out Figured_mahogany_pxr128_normal.png
sips -s format png Figured_rosewood_pxr128.tif --out Figured_rosewood_pxr128.png
sips -s format png Figured_rosewood_pxr128_bmp.tif --out Figured_rosewood_pxr128_bmp.png
sips -s format png Figured_rosewood_pxr128_normal.tif --out Figured_rosewood_pxr128_normal.png
sips -s format png Figured_sepele_pxr128.tif --out Figured_sepele_pxr128.png
sips -s format png Figured_sepele_pxr128_bmp.tif --out Figured_sepele_pxr128_bmp.png
sips -s format png Figured_sepele_pxr128_normal.tif --out Figured_sepele_pxr128_normal.png
sips -s format png Figured_yew_wood_pxr128.tif --out Figured_yew_wood_pxr128.png
sips -s format png Figured_yew_wood_pxr128_bmp.tif --out Figured_yew_wood_pxr128_bmp.png
sips -s format png Figured_yew_wood_pxr128_normal.tif --out Figured_yew_wood_pxr128_normal.png
sips -s format png Hackberry_pxr128.tif --out Hackberry_pxr128.png
sips -s format png Hackberry_pxr128_bmp.tif --out Hackberry_pxr128_bmp.png
sips -s format png Hackberry_pxr128_normal.tif --out Hackberry_pxr128_normal.png
sips -s format png Honduran_mahogany_pxr128.tif --out Honduran_mahogany_pxr128.png
sips -s format png Honduran_mahogany_pxr128_bmp.tif --out Honduran_mahogany_pxr128_bmp.png
sips -s format png Honduran_mahogany_pxr128_normal.tif --out Honduran_mahogany_pxr128_normal.png
sips -s format png Marine_plywood_pxr128.tif --out Marine_plywood_pxr128.png
sips -s format png Marine_plywood_pxr128_bmp.tif --out Marine_plywood_pxr128_bmp.png
sips -s format png Marine_plywood_pxr128_normal.tif --out Marine_plywood_pxr128_normal.png
sips -s format png Quartered_sepele_pxr128.tif --out Quartered_sepele_pxr128.png
sips -s format png Quartered_sepele_pxr128_bmp.tif --out Quartered_sepele_pxr128_bmp.png
sips -s format png Quartered_sepele_pxr128_normal.tif --out Quartered_sepele_pxr128_normal.png
sips -s format png Quartered_teak_pxr128.tif --out Quartered_teak_pxr128.png
sips -s format png Quartered_teak_pxr128_bmp.tif --out Quartered_teak_pxr128_bmp.png
sips -s format png Quartered_teak_pxr128_normal.tif --out Quartered_teak_pxr128_normal.png
sips -s format png Red_oak_pxr128.tif --out Red_oak_pxr128.png
sips -s format png Red_oak_pxr128_bmp.tif --out Red_oak_pxr128_bmp.png
sips -s format png Red_oak_pxr128_normal.tif --out Red_oak_pxr128_normal.png
sips -s format png Redwood_tree_bark_pxr128.tif --out Redwood_tree_bark_pxr128.png
sips -s format png Redwood_tree_bark_pxr128_bmp.tif --out Redwood_tree_bark_pxr128_bmp.png
sips -s format png Redwood_tree_bark_pxr128_normal.tif --out Redwood_tree_bark_pxr128_normal.png
sips -s format png Rough_cut_redwood_pxr128.tif --out Rough_cut_redwood_pxr128.png
sips -s format png Rough_cut_redwood_pxr128_bmp.tif --out Rough_cut_redwood_pxr128_bmp.png
sips -s format png Rough_cut_redwood_pxr128_normal.tif --out Rough_cut_redwood_pxr128_normal.png
sips -s format png White_maple_pxr128.tif --out White_maple_pxr128.png
sips -s format png White_maple_pxr128_bmp.tif --out White_maple_pxr128_bmp.png
sips -s format png White_maple_pxr128_normal.tif --out White_maple_pxr128_normal.png
sips -s format png White_oak_pxr128.tif --out White_oak_pxr128.png
sips -s format png White_oak_pxr128_bmp.tif --out White_oak_pxr128_bmp.png
sips -s format png White_oak_pxr128_normal.tif --out White_oak_pxr128_normal.png
